version: '3'
services:
  frontend:
    container_name: frontend
    build: 
      context: ./mindmap-frontend
    ports:
      - "3000:3000"
    networks:
      - mga
    depends_on:
      - backend
    volumes:
      - ./mindmap-frontend/src:/frontend/src
  backend:
    container_name: backend
    build: ./mindmap-backend
    ports:
      - "8090:8090"
    networks:
      - mga
    volumes:
      - ./mindmap-backend:/backend

networks:
  mga:
    driver: bridge
    external: false